default_diffusion:
  model_name: "openai_guided_diffusion_cifar"
  image_size: 32
  num_inference_steps: 80
  step_size: 0.02
  batch_size: 16
  guidance_scale: 1.5

client_level:
  enabled: true
  num_reconstruct_per_target: 64
  topk_candidates: 0
  loss_weights:
    grad: 1.0
  diffusion: "default_diffusion"

class_level:
  enabled: true
  num_reconstruct_per_target: 32
  topk_candidates: 0
  loss_weights:
    grad: 1.0
    cls: 0.5
  diffusion: "default_diffusion"

sample_level:
  enabled: true
  num_reconstruct_per_target: 256
  topk_candidates: 5
  loss_weights:
    grad: 1.0
    cls: 1.0
  diffusion: "default_diffusion"
